"""Initial tables

Revision ID: 3bc08c0cd893
Revises: 
Create Date: 2024-08-21 00:34:57.520065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc08c0cd893'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Сокращенное наименование'),
    sa.Column('fullname', sa.String(length=300), nullable=False, comment='Полное наименование'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Статус'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_title'), 'organizations', ['title'], unique=False)
    op.create_table('line_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=16), nullable=False),
    sa.Column('order_create_date', sa.DateTime(timezone=True), nullable=False, comment='Дата заказа'),
    sa.Column('costumer_contact_phone', sa.String(length=15), nullable=False, comment='Телефон заказчика'),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True, comment='Заказ выполнен'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_orders_costumer_contact_phone'), 'line_orders', ['costumer_contact_phone'], unique=False)
    op.create_index(op.f('ix_line_orders_id'), 'line_orders', ['id'], unique=False)
    op.create_index(op.f('ix_line_orders_order_create_date'), 'line_orders', ['order_create_date'], unique=False)
    op.create_index(op.f('ix_line_orders_order_number'), 'line_orders', ['order_number'], unique=False)
    op.create_index(op.f('ix_line_orders_organization_id'), 'line_orders', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_orders_organization_id'), table_name='line_orders')
    op.drop_index(op.f('ix_line_orders_order_number'), table_name='line_orders')
    op.drop_index(op.f('ix_line_orders_order_create_date'), table_name='line_orders')
    op.drop_index(op.f('ix_line_orders_id'), table_name='line_orders')
    op.drop_index(op.f('ix_line_orders_costumer_contact_phone'), table_name='line_orders')
    op.drop_table('line_orders')
    op.drop_index(op.f('ix_organizations_title'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
